site:
    baseUrl: https://swiftonserver.com/
    language: en-US
    title: Swift on server
    description: Articles about server-side Swift development. Created by Joannis Orlandos and Tibor BÃ¶decs.
    dateFormat: "yyyy-MM-dd HH:mm:ss"
